import React, { useState, useRef } from 'react';
import { FileText, Download, Printer, Filter, Calendar } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { useBiometricStore } from '../../store/useBiometricStore';
import { exportToCSV } from '../../lib/utils';
import { toast } from 'sonner';

export const ReportsPage: React.FC = () => {
  const { attendance } = useBiometricStore();
  const [reportType, setReportType] = useState('daily');
  const printRef = useRef<HTMLDivElement>(null);

  const handleExportCSV = () => {
    exportToCSV(`biometric_${reportType}_report`, attendance);
    toast.success(`Exported ${reportType} attendance report to CSV!`);
  };

  const handlePrint = () => {
    if (!printRef.current) return;

    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast.error('Please allow pop-ups to print reports');
      return;
    }

    const reportTitle = reportType === 'daily' ? 'Daily Attendance Audit' :
                       reportType === 'late' ? 'Late Arrivals & Penalties' :
                       reportType === 'unknown' ? 'Unknown Face Incidents' :
                       'Camera Performance & Uptime';

    // Get the report content
    const reportContent = printRef.current.innerHTML;

    // Create a styled HTML document for printing
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${reportTitle} - ${new Date().toLocaleDateString()}</title>
          <style>
            * {
              margin: 0;
              padding: 0;
              box-sizing: border-box;
            }
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
              color: #000;
              background: #fff;
            }
            .report-header {
              text-align: center;
              margin-bottom: 30px;
              padding-bottom: 20px;
              border-bottom: 3px solid #000;
            }
            .report-header h1 {
              font-size: 24px;
              font-weight: bold;
              margin-bottom: 10px;
            }
            .report-header p {
              font-size: 14px;
              color: #666;
            }
            .report-info {
              margin-bottom: 20px;
              font-size: 12px;
            }
            .report-info p {
              margin: 5px 0;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }
            thead {
              background-color: #f3f4f6;
              border-bottom: 2px solid #000;
            }
            th, td {
              padding: 12px;
              text-align: left;
              border: 1px solid #ddd;
              font-size: 12px;
            }
            th {
              font-weight: bold;
              text-transform: uppercase;
              font-size: 11px;
            }
            tbody tr:nth-child(even) {
              background-color: #f9fafb;
            }
            .report-footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #ddd;
              text-align: center;
              font-size: 10px;
              color: #666;
            }
            @media print {
              body {
                padding: 20px;
              }
              @page {
                margin: 1cm;
              }
            }
          </style>
        </head>
        <body>
          <div class="report-header">
            <h1>Facial Recognition Attendance System</h1>
            <h2>${reportTitle}</h2>
            <p>Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
          </div>
          <div class="report-info">
            <p><strong>Report Type:</strong> ${reportTitle}</p>
            <p><strong>Total Records:</strong> ${attendance.length}</p>
            <p><strong>Date Range:</strong> ${new Date().toLocaleDateString()}</p>
          </div>
          ${reportContent}
          <div class="report-footer">
            <p>This report was automatically generated by the Facial Recognition Attendance System</p>
            <p>© ${new Date().getFullYear()} All Rights Reserved</p>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    
    // Wait for content to load then print
    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
      printWindow.close();
    }, 250);

    toast.success('Opening print dialog...');
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white flex items-center gap-2">
            <FileText className="w-6 h-6 text-primary" /> Executive Report Generator
          </h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Generate printable PDF, Excel, and CSV compliance reports.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={handlePrint} leftIcon={<Printer className="w-4 h-4" />}>
            Print Report
          </Button>
          <Button variant="primary" onClick={handleExportCSV} leftIcon={<Download className="w-4 h-4" />}>
            Export CSV
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {[
          { id: 'daily', title: 'Daily Attendance Audit', desc: 'Detailed hourly check-in logs' },
          { id: 'late', title: 'Late Arrivals & Penalties', desc: 'Grace period threshold violations' },
          { id: 'unknown', title: 'Unknown Face Incidents', desc: 'Security alerts and unassigned scans' },
          { id: 'camera', title: 'Camera Performance & Uptime', desc: 'RTSP bandwidth and node storage' },
        ].map((rep) => (
          <Card
            key={rep.id}
            glass
            onClick={() => setReportType(rep.id)}
            className={`p-4 cursor-pointer transition-all border ${
              reportType === rep.id
                ? 'border-primary ring-2 ring-primary/20 shadow-md'
                : 'hover:border-slate-300 dark:hover:border-slate-700'
            }`}
          >
            <h4 className="font-bold text-sm text-slate-900 dark:text-white">{rep.title}</h4>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{rep.desc}</p>
          </Card>
        ))}
      </div>

      <Card glass className="p-6">
        <CardHeader className="px-0 pt-0">
          <CardTitle>Report Preview: {reportType.toUpperCase()} Summary</CardTitle>
          <CardDescription>Generated on {new Date().toLocaleDateString()}</CardDescription>
        </CardHeader>
        <CardContent className="px-0 overflow-x-auto" ref={printRef}>
          <table className="w-full text-left text-xs border-collapse">
            <thead className="bg-slate-100 dark:bg-slate-900/60 font-semibold border-b border-slate-200 dark:border-slate-800">
              <tr>
                <th className="p-3">Record ID</th>
                <th className="p-3">Member Name</th>
                <th className="p-3">Department</th>
                <th className="p-3">Clock In</th>
                <th className="p-3">Confidence</th>
                <th className="p-3">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60">
              {attendance.map((rec) => (
                <tr key={rec.id}>
                  <td className="p-3 font-mono">{rec.id}</td>
                  <td className="p-3 font-bold">{rec.userName}</td>
                  <td className="p-3">{rec.department}</td>
                  <td className="p-3 font-mono">{rec.clockIn}</td>
                  <td className="p-3 font-mono">{rec.confidenceScore}%</td>
                  <td className="p-3 uppercase font-semibold">{rec.status}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </CardContent>
      </Card>
    </div>
  );
};
